version: '3'
services:
  influxdb:
    image: influxdb:1.8
    restart: always
    volumes:
      - "./influxdb:/var/lib/influxdb"
      - "./influxdb/conf:/etc/influxdb/"
    ports:
      - "8086:8086"

  mqtt_to_influxdb:
    image: mqtt_to_influxdb
    restart: always
    links:
      - influxdb
      - mosquitto
    environment:
      - PYTHONUNBUFFERED=1

  mosquitto:
    image: eclipse-mosquitto:1.6
    restart: always
    volumes:
      - "./mosquitto:/mosquitto"
    ports:
      - "1883:1883"

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    user: "0"
    volumes:
      - "./grafana/data:/var/lib/grafana"
    links:
      - influxdb
    ports:
      - "3000:3000"
